### ISSUE TITLE
[Both] Topbar layout overlapping

### ISSUE THREAD

**Issue by Nightmare987** [harbassan/spicetify-apps#116]
I AM ON A MACBOOK AIR

<img width="1173" alt="Screenshot 2024-06-28 at 7 47 05 PM" src="https://github.com/harbassan/spicetify-apps/assets/96702441/a01ea835-5251-4df3-a30a-f803e977fe07">

- the titles overlap
- there is no album page
- i also cannot click on the timeframe option, the settings, or whatever is in the middle of the two

ADDITION:
- also cannot use filters or top right options for the library app
- library app also has overlapping titles
<img width="1162" alt="Screenshot 2024-06-29 at 1 33 10 AM" src="https://github.com/harbassan/spicetify-apps/assets/96702441/984d4e2f-d549-4b09-bfd9-c11b618824c1">

**Comment by hyunicode** [comment]
just add snippet

```css
#stats-app > .contentSpacing{
  padding: 40px !important;
}
#library-app > .contentSpacing{
  padding: 40px !important;
}
```

<img width="1920" alt="image" src="https://github.com/user-attachments/assets/5ec5eb29-f7fc-4d09-bfe5-7f7dbe1da754">

**Comment by endeay** [comment]
> just add snippet

How?

**Comment by hyunicode** [comment]
> > just add snippet
> 
> How?

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/bb9060bd-728a-4a6d-a45c-23dccf545320">

```
#stats-app > .contentSpacing{
  padding: 40px !important;
}
#library-app > .contentSpacing{
  padding: 40px !important;
}
```

**Comment by pertoh** [comment]
How can you add a index.js which is missing?

**Comment by Filip1432** [comment]
hyunicode how did you make the top bar so clean?

**Comment by hyunicode** [comment]
> hyunicode how did you make the top bar so clean?

theme: https://github.com/Astromations/Hazy

**Comment by AineshXCR7** [comment]
> > hyunicode how did you make the top bar so clean?
> 
> theme: https://github.com/Astromations/Hazy

I did installed the theme but dont know how to get a clean top bar as yours can you explain it further it will be much appreciated?

**Comment by hyunicode** [comment]
> > > hyunicode how did you make the top bar so clean?
> > 
> > 
> > theme: https://github.com/Astromations/Hazy
> 
> I did installed the theme but dont know how to get a clean top bar as yours can you explain it further it will be much appreciated?

Here is my custom snippet (it works great on Mac)
```css
* {
  font-family: 'Comic Sans MS' !important;
}
#stats-app > .contentSpacing {
  padding: 40px !important;
}
#library-app > .contentSpacing {
  padding: 40px !important;
}
.marketplace-header {
  display: inline-flex;
  padding-top: 0 !important;
  position: relative;
  margin-bottom: 40px;
}
.lyrics-config-button-container,
.lyrics-lyricsContainer-Provider {
  display: none;
}
.main-globalNav-searchSection {
  margin-left: 50px;
}
button[aria-label='Hazy Settings'] {
  display: none !important;
}
.main-globalNav-searchSection {
  width: fit-content !important;
  position: relative !important;
}
.custom-navlinks-scrollable_container {
  max-width: unset !important;
}
.main-topBar-whatsNewFeed,
.main-topBar-buddyFeed {
  display: none !important;
}
button.search-searchCategory-carouselButton {
  display: none !important;
}
button[class~='main-globalNav-link-icon'],
button[class~='main-globalNav-icon'],
button[class~='main-topBar-topbarContentRight'] {
  background-color: transparent !important;
}
```

<img width="1512" alt="Image" src="https://github.com/user-attachments/assets/9d9fb5d1-6bea-4e09-9136-8a3c4fc18972" />
